version: "3.8"

services:
  front:
    # El nombre del contenedor se toma de la variable ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL}
        - VITE_STORAGE_ENCRYPTION_KEY=${STORAGE_ENCRYPTION_KEY}
        - BUILD_SCRIPT=${BUILD_SCRIPT_ARG}
    ports:
      - "${PORT}:80"
    restart: always
